services:
  boobs:
    image: asskoala/koalabot
    user: node
    environment:
      - NODE_ENV=production
    volumes:
      - ../logs:/logs
      - ../data:/data
      - ./environment/dotenv-prod.txt:/boobs/bot/.env
      - ../temp:/temp
    restart: always
